project:
  type: website

website:
  title: "Research Ring"
  navbar:
    tools:
    logo: "www/research_ring_hex.png"
    right:
      # - href: index.qmd #this needs to stay "index.qmd" to be recognized as the landing page
      #   text: Home
      - about.qmd
      - research_processes.qmd
      - lab_posts/posts.qmd
  sidebar: 
    - title: "Research Processes"     
      contents:
        - research_processes.qmd
        - getting_started.qmd
        - working_with_a_team.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

